---
title: "Homework 1"
author: "Shaina Trevino"
date: "January 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating new visualizations through joins

#### _An exploration of Kaggle's open university learning analytics dataset_

### Background

For this homework we will use data from the online data science platform [kaggle](https://www.kaggle.com/). Kaggle is an online data science platform that began as a competitive platform for predictive modeling problems. Private organizations would offer a prize, usually in the range of \$25K-$100K, for the individual or team that could provide the best predictive model for their problem. This is still a primary function of the website (see active competitions [here](https://www.kaggle.com/competitions>)), but the website has grown and is now also a place to share datasets, compete in open competitions (where you can see others code), and generally learn different facets and approaches to data science in an applied way.

#### Getting Started

You can download the data we’ll use for this homework either from kaggle (requires you create an account with [kaggle](https://www.kaggle.com/rocki37/open-university-learning-analytics-dataset)) or [directly from the organization](https://analyse.kmi.open.ac.uk/open_dataset). The latter link is worth examining to learn more about the data, regardless.

A total of seven datasets (tables) related to an online learning analytics project should be included with your download. A number of keys link the various sources of data. I recommend reading through the documentation provided by the organization to better understand these keys.

### Assignment

This primary components of this assignment are highly open-ended. These are to

1. Use at least 3 mutating joins
1. Use at least 1 filtering join
1. Produce at least 3 data displays

Following the completion of these requirements, please reproduce the following figure.